/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UnsafeReflection */

#ifndef _Included_UnsafeReflection
#define _Included_UnsafeReflection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UnsafeReflection
 * Method:    getUnsafe
 * Signature: ()Lsun/misc/Unsafe;
 */
JNIEXPORT jobject JNICALL Java_ro_comodinoh_mirror_Mirror_getUnsafe
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
